apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-game-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game2048
  template:
    metadata:
      labels:
        app: game2048
    spec:
      containers:
        - name: game2048-container
          image: alexwhen/docker-2048
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: game-service-2048
spec:
  selector:
    app: game2048
  ports:
    - protocol: TCP
      port: 5858
      targetPort: 80

