apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana-for-game
spec:
  rules:
  - host: gane-siddhartha-version.upes-int-devops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-siddhartha-ns
            port:
              number: 80
  ingressClassName: nginx